### ISSUE TITLE
"ImGuiNET.RangePtrAccessor" not found

### ISSUE THREAD

**Issue by PixelDough** [Mezo-hx/MonoGame.ImGuiNet#8]
After following the new instructions to install this, any attempts I make to use it result in a crash when `EndLayout` is called

```
Unhandled exception. System.MissingMethodException: Method not found: 'ImGuiNET.RangePtrAccessor`1<ImGuiNET.ImDrawListPtr> ImGuiNET.ImDrawDataPtr.get_CmdListsRange()'.
   at MonoGame.ImGuiNet.ImGuiRenderer.UpdateBuffers(ImDrawDataPtr drawData)
   at MonoGame.ImGuiNet.ImGuiRenderer.RenderDrawData(ImDrawDataPtr drawData) in C:\Users\PixelDoughAdmin\Documents\Repos\monogame_project\MonoGame.ImGuiNet-main\MonoGame.ImGuiNet\ImGuiRenderer.cs:line 308
   at MonoGame.ImGuiNet.ImGuiRenderer.EndLayout() in C:\Users\PixelDoughAdmin\Documents\Repos\monogame_project\MonoGame.ImGuiNet-main\MonoGame.ImGuiNet\ImGuiRenderer.cs:line 134
```

My project is using net6.0 and C# 11.0, in case that helps, but I have tried a couple other versions and had the same results

**Comment by PixelDough** [comment]
Ah, figured out the issue. I had ImGui.NET installed in my game project, which was causing an issue with the one that is within MonoGame.ImGuiNet. Went into NuGet and removed ImGui.NET from my game and it now works
